name: Flutter Android workflow

on: [push, workflow_dispatch]
jobs:
  build:
    name: Create Android App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - name: Disable flutter telemetry
        run: flutter --disable-telemetry
      - name: Disable dart telemetry
        run: dart --disable-analytics
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Build Android App Bundle
        run: flutter build appbundle
      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-unsigned
          path: build/app/outputs/bundle/release/app-release.aab
